// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/dashboard/home_page.dart' as a1;
import 'app/login/login_page.dart' as a0;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          a0.LoginPage(),
        ),
      ),
      RouteEntity(
        key: '/dashboard',
        uri: Uri.parse('/dashboard'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.HomePage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  login: '/login',
  dashboard: (
    path: '/dashboard',
    home: '/dashboard/home',
  ),
);
